theme: jekyll-theme-midnight
title:
name: Site de la Bocauthèque
description: Expérimentations alimentaires & agricoles
logo: logo-labo.png

plugins:
  - jekyll-sitemap


collections:
  fournisseurs:
    output: true
    permalink: /fournisseurs/:path
