theme: jekyll-theme-midnight
title: La Bocauthèque
name: Site de la Bocauthèque
description: Lieu pour cultiver & transformer
logo: https://damienchivialle.github.io/bocautheque/assets/img/logo_bocautheque1.png

plugins:
  - jekyll-sitemap


collections:
  fournisseurs:
    output: true
    permalink: /fournisseurs/:path
