theme: jekyll-theme-midnight
title: Bocauthèque
name: Site de la Bocauthèque
description: Projet de mise en bocaux
logo: https://centime.github.io/bocautheque/assets/img/logo.png

plugins:
  - jekyll-sitemap


collections:
  fournisseurs:
    output: true
    permalink: /fournisseurs/:path
