theme: jekyll-theme-midnight
title: La Bocauthèque
name: Site de la Bocauthèque
description: Espace test agricole & alimentaire
logo: 

plugins:
  - jekyll-sitemap


collections:
  fournisseurs:
    output: true
    permalink: /fournisseurs/:path
